server:
  port: ${BASE_PORT:8080}
  servlet:
    context-path: ${BASE_URL:/v1/myshop}

spring:
  application:
    name: myshop
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_ADDR:localhost}:${DB_PORT:5432}/${DB_DATABASE:myshop}

  # Setup for SpringBoot support Handle 404 Not-found on unknown endpoint
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  secret: chicken
  expiresIn: 6000
  issuer: NashTech



